server:
  port: 9001
spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false #mysql 5.7以后安全加固，需要配置是否开启ssl
    username: root
    password: 123456
  devtools:
    restart:
      poll-interval: 3s
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.evil.cloud.entities #mapper会从这里找别名对应的实体类
