server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh
          uri: lb://payment-service #通过服务名路由,lb://serviceName是springcloud gateway在微服务中自动为我们创建的负载均衡
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          uri: lb://payment-service
          predicates:
            - Path=/payment/create/**

#  cloud:
#    gateway:
#      routes:
#        - id: payment_routh #路由的id，要唯一，做好和服务名相关联
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/**  #断言，路径相匹配将进行路由
#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/create/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com/eureka