server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/misa_739/springcloudLearn-config.git #git仓库
          #uri: git@github.com:zzyybs/springcloud-config.git
          search-path:  #搜索目录
            - springcloudLearn-config
      label: master #读取分支
  ##rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'