server:
  port: 8802

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:  #这里配置需要绑定的rabbitmq的服务信息
        defaultRabbit:  #表示定义的名称，用于与binding整合
          type: rabbit  #消息组件类型
          environment:  # 设置rabbitmq的相关环境
            spring:
              rabbitmq:
                host: 10.10.10.185
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input:
          destination: studyExchange  #表示要使用的Exchange的名称
          content-type: application/json  #设置消息类型，json，文本则要设置为text/plain
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔（默认30s）
    lease-expiration-duration-in-seconds: 5 #超过5s（默认90s）
    instance-id: receive-8802.com  #在信息列表中显示主机名称
    prefer-ip-address: true #访问的路径变为IP地址